### ISSUE TITLE
Name?

### ISSUE THREAD

**Issue by jakirkham** [zarr-developers/zarr-specs#1]
Have named this `spec` for lack of creativity. Though maybe it should be `zarr-spec` or something else to aid users forking the repo and to avoid conflicts with similarly named things. There may be other good choices for a name. If people have suggestions, feel free to voice them. Maybe we can pick the best name by consensus?

**Comment by alimanfoo** [comment]
Thanks @jakirkham for setting this up. FWIW I would vote for "zarr-spec" just to avoid conflicts when forking. Or possibly even "zarr-specs" if we end up putting both the storage spec and a codec registry in here (although what is in scope for this repo probably should have its own issue...)

**Comment by alimanfoo** [comment]
I took the liberty to rename this repo "zarr-specs", shout if any objections.

**Comment by jakirkham** [comment]
Sure, meant to say SGTM. :)

Closing since we seem to have solved this one. ;)

**Comment by ryan-williams** [comment]
Slightly tangential and probably not feasible, but it would be nice if we could get the [seemingly-inactive `zarr` handle](https://github.com/zarr) and use it for the organization, instead of `zarr-developers`.

**Comment by joshmoore** [comment]
I've had success requesting in the past, with the caveat that the user could have private repositories that are in use which we wouldn't see.

**Comment by alimanfoo** [comment]
I'd be happy to send an email to see if they might give us "zarr".

If they did grant permission, logistically how would it work? They rename themselves to something else, then we rename the "zarr-developers" organisation to "zarr"?

**Comment by jakirkham** [comment]
I’d be in favor of at least asking. Worst case they say no and nothing really changes.

**Comment by joshmoore** [comment]
@alimanfoo : I think so, yes. The renaming support tends to work quite well.

**Comment by alimanfoo** [comment]
I've sent an email asking if we might have "zarr", fingers crossed.
