### ISSUE TITLE
Would like to be involved in spec change discussions. 

### ISSUE THREAD

**Issue by tam203** [zarr-developers/zarr-specs#10]
Hello @alimanfoo pointed me in this direction following my post on a desired spec at zarr-developers/zarr-specs/#9 .

I'd be really keen to get involved with these discussion/calls. 

At the Met Office we've lots of big fast-moving data that most (all) formats currently struggle with.

**Comment by joshmoore** [comment]
@tam203 :+1: see https://github.com/zarr-developers/zarr/issues/315#issuecomment-458513132 for coordinates for the next call (short answer, **March 27th**). It would be good if you could introduce you and your problems at the start. (Others' whacks at that are in the [notes](https://docs.google.com/document/d/1o-xSVe1iAKNIfz2a9U0-90-z96XwwTT9jzp-ZuyOJQc/edit#heading=h.m4je4muv1dzi))

**Comment by jakirkham** [comment]
It would be great to have you at the meeting @tam203.

As it appears your question is answered, am going to go ahead and close this. We look forward to seeing you around more :)
