### ISSUE TITLE
Name conventions for zarr

### ISSUE THREAD

**Issue by DennisHeimbigner** [zarr-developers/zarr-specs#114]
I gather from the V2 spec that the notion of a legal name for arrays, groups, and attributes is taken wholesale from h5py, which in turn means that the HDF5 name rules are used.
Is this correct?

**Comment by shoyer** [comment]
Informally, I think the main rule is that identifiers (at least for arrays and groups) should be valid file names (most notably, not including /`). Obviously there are platform specific differences, but I would guess that at least roughly aligns with HDF5, too.

**Comment by DennisHeimbigner** [comment]
I will mention that netcdf had a lot of trouble early on by not being
very explicit about the legal name rules. The situation here is, as you note,
somewhat different, because zarr conflates its legal names with the legal file system names. I will predict that this will come back to bite you in the future. But we shall see.

**Comment by dopplershift** [comment]
It sounds like the current situation is basically implementation-defined, and should probably be codified in the spec. The first thing that comes to mind is how "valid file names" intersects with case-insensitive file systems.

**Comment by joshmoore** [comment]
In V2, I assume "[any] ASCII string" would hold: https://zarr.readthedocs.io/en/stable/spec/v2.html#storage unless we agree on and add the informal rules to https://github.com/zarr-developers/zarr-python/blob/master/docs/spec/v2.rst

In V3 the current constraints are in https://zarr-specs.readthedocs.io/en/core-protocol-v3.0-dev/protocol/core/v3.0.html#node-names:

> * must not be the empty string (“”)
> * must consist only of characters in the sets a-z, A-Z, 0-9, -_.
> * must not be a string composed only of period characters, e.g. “.” or “..”
> * must be at most 255 characters long
> * Node names are case sensitive, e.g., the names “foo” and “FOO” are not identical.
