### ISSUE TITLE
v3: https://purl.org/zarr/spec/codec/XXX/1.0: codec singular or codecs plural ?

### ISSUE THREAD

**Issue by rouault** [zarr-developers/zarr-specs#116]
https://github.com/zarr-developers/zarr-specs/blob/core-protocol-v3.0-dev/docs/protocol/core/v3.0.rst mentions in examples ``"codec": "https://purl.org/zarr/spec/codec/gzip/1.0"`` (codec singular) whereas https://github.com/zarr-developers/zarr-specs/blob/core-protocol-v3.0-dev/docs/codecs/gzip/v1.0.rst mentions ``"codec": "https://purl.org/zarr/spec/codecs/gzip/1.0"`` (codec plural).

**Comment by joshmoore** [comment]
Thanks, @rouault. I pushed an update. All the best, ~Josh

**Comment by rouault** [comment]
There was another occurence. Proposed fix in https://github.com/zarr-developers/zarr-specs/pull/117

@alimanfoo  Zarrita use codec singular. It should likely be updated

**Comment by joshmoore** [comment]
> @alimanfoo Zarrita use codec singular. It should likely be updated

That poses an interesting problem:

```
zarr_implementations $ git grep spec/codec
examples/zarrita.zr3/meta/root/blosc/lz4.array.json:        "codec": "https://purl.org/zarr/spec/codec/blosc/1.0",
examples/zarrita.zr3/meta/root/gzip.array.json:        "codec": "https://purl.org/zarr/spec/codec/gzip/1.0",
examples/zarrita.zr3/meta/root/zlib.array.json:        "codec": "https://purl.org/zarr/spec/codec/zlib/1.0",
(base) /opt/zarr_implementations $
```
as well as https://github.com/xtensor-stack/xtensor-zarr/blob/484f98bd06c53e7dc3d1653612907c479954259f/include/xtensor-zarr/xzarr_array.hpp#L40

I took the plural because it was more prevalent in the spec doc, but looks like the singular has made it out into the wild.

**Comment by davidbrochart** [comment]
We can make the change in xtensor-zarr.

**Comment by joshmoore** [comment]
Please see https://github.com/zarr-developers/zarr-specs/pull/119 for the move to the singular version.

cc: @alimanfoo @Carreau
