### ISSUE TITLE
GeoZarr Extension

### ISSUE THREAD

**Issue by christophenoel** [zarr-developers/zarr-specs#124]
Dear Community,

In the context of an European Space Agency (ESA) GSTP (General Support Technology Programme) we prepared a first draft for a geospatial extension to Zarr (GeoZarr).

This specification is an early draft (v0.1) and a prototype implementation of GeoZarr-based (and Cloud based) geospatial data store has been demonstrated to the Agency in the frame of the project. We are also developing a map viewer (based on OpenLayers) to demonstrate multiscaling and integration of the store in an Earth Observation catalogue.

If you have any interest in Space domain, we would be very interested to get your feedback and ideas to consolidate this extension. We mostly based the specification on what xarray already supports. 

Here is the repository: https://github.com/christophenoel/geozarr-spec/blob/main/geozarr-spec.md

Kind regards,

Christophe Noël, Spacebel.

**Comment by jakirkham** [comment]
Have gone ahead and transferred this issue to zarr-specs since it seems like we are ok with that

**Comment by joshmoore** [comment]
@christophenoel, I've just added https://github.com/zarr-developers/zarr-specs/issues/125 which will be ramping up over the course of the next week or two. Hopefully this would help us to refactor any of the shared issues from the multiscale conventions into a shared document.

**Comment by christophenoel** [comment]
> It would be great to align efforts. I will try to review your spec over the next week.
Hi Ryan, it tried to reach you by email unsuccessfully. I will be working on this by mid february.

**Comment by christophenoel** [comment]
Dear all,

I'm very happy to share with you a first bunch of resources (presentatins, demos) presenting the project, and showing the assets of GeoZarr.

We finally refined the multiscales support and recently introduced visual portrayals and symbology (see OGC WMS SLD) directly in the data to facilitate the display on map viewers.

I hope this helps ! 

Christophe.

--- 

Specification [Document](geozarr-spec.md) - [Change Log](https://github.com/christophenoel/geozarr-spec/wiki)

Demonstration Videos ([Youtube channel](https://youtube.com/playlist?list=PLzPGC4s5HQOPdeLoK1MXK6gEa1x2Az8Dn)):
- Project Presentation (at WGISS-53) [GeoZarr Data Store - Context of the ESA GSTP project](https://youtu.be/NYhh66EstnY)
- Project Presentation (at DAP) [Hyperspectral Data Store and Access Project](https://youtu.be/CfmPppVR-o4)
- Demo: [GeoZarr Visual Portrayals and OpenLayers extension](https://youtu.be/IKURmv6CVGU)
- Demo: [GeoZarr Fast Time Series Plotting](https://youtu.be/Nt1URJqW71o)
- Demo: [GeoZarr Compute and plot NDWI index at runtime](https://youtu.be/UP0DjphdZgM)
- Demo: [GeoZarr Catalogue Integration](https://youtu.be/Nlbo3FJH8lo)
- Demo: [GeoZarr Serverless Visualisation and Pixel-Based Access](https://youtu.be/sKlejJcPKqQ)
- Comparison: [GeoZarr vs COG Performances](https://youtu.be/KGC8mLqlsCs)

OpenLayers extension prototype: https://github.com/spacebel/geozarr-openlayers

**Comment by aurghs** [comment]
That's very interesting!

**Comment by joshmoore** [comment]
Thanks, @christophenoel. :+1: I've passed your comment on to the github.com/ome/ngff folks as well. You might be interested in further iterations to the OME-Zarr spec built on top of multiscales, e.g. [Transformation types](https://github.com/ome/ngff/issues/101) from @bogovicj. If you have any thoughts or just general interest in discussing ways of sharing updates to a base spec, let me/us know, here or possibly at a [regular community call](https://github.com/zarr-developers/community/issues/1) (which happens to be today).

All the best,
~Josh

**Comment by joshmoore** [comment]
@christophenoel: you might be interested in https://github.com/ome/ngff/pull/114 which resulted from discussion with various xarray-affine folks.

cc: @thewtex @malmans2 @TomNicholas @aurghs

**Comment by briannapagan** [comment]
Can this be closed in light of: https://github.com/zarr-developers/geozarr-spec
