### ISSUE TITLE
v3 spec development process & milestones

### ISSUE THREAD

**Issue by alimanfoo** [zarr-developers/zarr-specs#13]
Repurposing this issue to discuss process and milestones for development of the v3 protocol spec.

Straw man proposal for discussion:

* **Phase 1 (current)**
  * Continue discussing technical points in the current editor's draft via zarr-specs github and the v3 spec dev calls 
  * Accumulate some early implementation experience from zarr-python (Matthias), zarrita (Alistair), and at least one other language (ideally statically-typed)
  * Take tentative positions on any remaining open questions, update and complete the v3 protocol and associated specs, highlighting any particular points where we'd like feedback
  * **Milestone: Publish "First Working Draft"**
  * Request for comments
* **Phase 2**
  * Accumulate some more implementation experience, continue technical discussions
  * Compile and discuss comments from community review on first working draft, decide how to address comments
  * Revise v3 protocol spec
  * Establish a test suite for verifying completeness and compatibility between different implementations
  * **Milestone: Publish "Second Working Draft"**
  * Call for implementations
* **Phase 3**
  * Focus on implementations, getting completeness and compatibility 
  * Deal with any further (hopefully minor) technical issues that arise from new implementations
  * Finalise v3 protocol and associated specs
  * Request approval from Zarr Steering Group to publish 
  * **Milestone: Publish "Recommendation"**

**Comment by alimanfoo** [comment]
cc @Carreau

**Comment by alimanfoo** [comment]
Btw also open to a simpler process. E.g., proposal above has three publication milestones (First Working Draft, Second Working Draft, Recommendation), but we could also try a simpler process with just two publication milestones (First Working Draft, Recommendation).

Either way, I think it's important we have some publication milestones so we can show progress and there's a clear point of engagement for implementers.

**Comment by jstriebel** [comment]
We're following the ZEP process now, (see [ZEP 0](https://zarr.dev/zeps/active/ZEP0000.html)), and just posted an update on the next steps: https://zarr.dev/blog/zep1-update. Closing this issue for now.
