### ISSUE TITLE
Chunk key encoding

### ISSUE THREAD

**Issue by jbms** [zarr-developers/zarr-specs#172]
There are a few issues with the encoding of chunk (and shard) keys that I'd like to raise.

With the current v3 spec, a chunk at position `(x, y, z)` is encoded as `cx/y/z` by default.  The same naming convention is also used for shards under the sharding extension.

The only customization currently supported is via the `chunk_grid/separator` metadata value.  The current specification doesn't describe any requirements on that field; it just provides a few examples.

At the very least, we should properly specify that field, and should constrain it to either "/" or "." as in the zarr v2 specificatio. 
 As discussed in the context of the zarr v2 `dimension_separator` field, allowing arbitrary separators can lead to ambiguities and there aren't any known use cases.

However, there are a few other issues with this encoding:

In many cases, the underlying store will be ordered and support range queries on keys, meaning listing all the keys lexicographically >= a start key and lexicographically < an end key.  For example, S3, GCS, and most ordered database tables.  More sophisticated stores may support additional operations, like efficiently querying the total number of bytes stored within a key range, without enumerating all of the keys.  If we choose the encoding of zarr chunks as keys appropriately, we can take advantage of this operation to efficiently determine whether a given subregion of the array contains any data (or possibly how much data).  

When processing a large array that is sparsely written (i.e. not all chunks are present), this type of query allows us to efficiently skip empty regions of the array.

Unfortunately, the current key encoding in the zarr v3 spec is not optimal for use with range queries:
1. Lexicographical order does not match numeric order: "c10" is lexicographically less than "c9"
2. While we support both C and F order for encoding individual chunks, the key encoding always corresponds (aside from point 1) to C order.  In most cases, it would probably be desirable for the key encoding to match the chunk encoding, but in general the user should be able to choose any order.

Regarding point 1, I think there was a comment on ZEP 1 to use zero padding when encoding chunk keys, but I'm having trouble finding it.  The drawback to zero padding is that we have to choose a fixed amount of zero padding, which may not be sufficient if we resize the array.  We could always use the maximum possible amount of zero padding (assuming array bounds are limited to 64-bit integer) but then the keys may be annoyingly long.  The advantage to zero padding is that it remains extremely readable.

There are variable-length encodings of numbers where lexicographical order matches numeric order.  For example, such a scheme is used by UTF-8.  A simpler alternative might be to prefix each component with the number of digits, in base 16.  E.g. instead of "c10" and "c9" we would have "210" and "19".

It is indeed fairly straightforward to define extensions that change the key encoding, so arguably we could defer this issue until later.  However, the current key encoding in the spec is not optimal for anything, except perhaps human readability, so it may be worthwhile to improve it even if we defer some key encoding improvements (e.g. morton order) to extensions.

**Comment by jstriebel** [comment]
> The only customization currently supported is via the chunk_grid/separator metadata value. The current specification doesn't describe any requirements on that field; it just provides a few examples.
>
> At the very least, we should properly specify that field, and should constrain it to either "/" or "." as in the zarr v2 specificatio.
As discussed in the context of the zarr v2 dimension_separator field, allowing arbitrary separators can lead to ambiguities and there aren't any known use cases.

Good point, let's do this!

> It is indeed fairly straightforward to define extensions that change the key encoding, so arguably we could defer this issue until later. However, the current key encoding in the spec is not optimal for anything, except perhaps human readability, so it may be worthwhile to improve it even if we defer some key encoding improvements (e.g. morton order) to extensions.

I'd rather leave this as an extension for now, mainly to go forward with v3 soon. However, if there was a PR to change this and there's large agreement, I'm not opossed to such a such a change (I think the argument and feature are valid and useful!), I'm just worried about slowing down a finalized v3 further.

> Regarding point 1, I think there was a comment on ZEP 1 to use zero padding when encoding chunk keys, but I'm having trouble finding it.

You're probably referring to isse #64?

**Comment by jbms** [comment]
Yes, agreed.

**Comment by jbms** [comment]
I have been thinking a bit more about this feature.  While I don't want to add any additional functionality to v3.0, I think it might be worth changing the metadata representation a bit:

Currently we have array metadata of the form:

```json
{"chunk_grid": {"name": "regular", "configuration": {"chunk_shape": [100, 100], "separator": "/"}}, ...}
```

I'm proposing that we instead have:

```json
{"chunk_grid": {"name": "regular", "configuration": {"chunk_shape": [100, 100]}}, "chunk_key_encoding": {"name": "simple", "configuration": {"separator": "/"}}, ...}
```

This change decouple the chunk grid definition from the encoding of chunk keys, which I think makes sense for the following reasons:

- We expect to have at least two chunk grids: the regular chunk grid, and the rectilinear chunk grid proposed in the (draft) zep 3.
- As I noted in the initial comment above, for efficiency reasons it is important to support alternative chunk key encodings so that the lexicographical ordering of the keys is more meaningful.  Any such alternative chunk key encoding would be equally applicable to both the regular chunk grid and to the rectilinear chunk grid.  The existing "separator" option is of course also equally applicable to both regular and rectilinear chunk grids.
- When using sharding, individual chunks no longer have a meaningful chunk key.  Instead we need to assign keys to shards.  The existing sharding proposal just takes the `separator` parameter from the chunk grid and uses it for the shard keys as well.  That works, but it is in my view somewhat confusing to reuse a parameter like that.

I believe separating the chunk key encoding from the chunk grid specification makes the metadata more logical and easier to understand.

An alternative variant to this proposal would be to make the `chunk_key_encoding` a property of the `chunk_grid` rather than a top-level property.  When using sharding, `chunk_key_encoding` would *not* be specified as part of the `chunk_grid` and would instead be specified as part of the sharding configuration.  That might logically make slightly more sense, though I prefer to just keep `chunk_key_encoding` as a top-level metadata property.

A possible objection is that chunk_key_encoding could be handled as a storage transformer.  That is true, and also applies to the existing `separator` option.  However, in order to take advantage of the efficiency gains, we would need the storage transformer interface implementation-wise to be even more elaborate.  And I don't think there is any advantage to the composability that making it a storage transformer would allow.

**Comment by jstriebel** [comment]
> I believe separating the chunk key encoding from the chunk grid specification makes the metadata more logical and easier to understand.

Good idea! I was wondering if we should also make the `c` prefix optional. This would allow to just add metadata to v2 datasets to make them v3 compatible without moving chunk data.

Sth. like
```json
"chunk_key_encoding": {
  "name": "simple",
  "configuration": {
    "separator": "/",
    "prefix": "c"
  }
}
```

where prefix can be `"c"` or `null`.

Not sure what the name would be, I'd rather use `default` or `decimal` than `simple`.

**Comment by rabernat** [comment]
I am on board with this!

**Comment by jstriebel** [comment]
Proposal from the current ZEP call:

```json
"chunk_key_encoding": {
  "name": "v2",
  "configuration": {
    "separator": "/",
  }
}
```

```json
"chunk_key_encoding": {
  "name": "default",
  "configuration": {
    "separator": "/",
  }
}
```
