### ISSUE TITLE
Issue overview: From URI to open array

### ISSUE THREAD

**Issue by jstriebel** [zarr-developers/zarr-specs#178]
This is a meta issue to track progress and ideas around opening stores. I think it would be a great goal to be able to:
1. Have a clear URI to a zarr hierarchy, group or array
  #132
3. Find data under this URI if you open it in a non-zarr-aware client
  #177
4. Can extract the root location and read the entrypoint metadata field from the URI (e.g. by using a `.zarr`/`.zr3` suffix? see #137)
  #192
5. Can open groups and arrays specified via URIs after 3:
    * Do we need store configuration in the entrypoint metadata or sth. similar?
      #65
    * Node names might need more clarification:
      * #56
      * #57
      * #77
      * #114

Also see
* #90
* https://github.com/ome/ngff/issues/144
* #175

**Comment by rabernat** [comment]
I plan to spend some time on this next week.

**Comment by jstriebel** [comment]
@rabernat Please also see @jbms's comment here: https://github.com/zarr-developers/zarr-specs/issues/177#issuecomment-1329839990

Do you both have time to join the ZEP meeting this Thursday to discuss this further in person? IMO this issue is the largest blocker for v3 atm and some in person discussions might help.

**Comment by rabernat** [comment]
Yes I will attend.

**Comment by jstriebel** [comment]
With #211 we have a minimal spec for opening URIs, at least for file stores. This is fine enough for now, further details like URIs for store + zarr-hierarchy path should be discussed in #132.
