### ISSUE TITLE
Adding resizing to spec

### ISSUE THREAD

**Issue by jakirkham** [zarr-developers/zarr-specs#188]
Currently zarr-python has the ability to resize (through a metadata change) arrays with no guarantee about how the underlying data changes. This is currently not in either v2 or v3 spec. Would be good to make this clearer.

cc @joshmoore @DennisHeimbigner @jstriebel

**Comment by jstriebel** [comment]
I agree, we should add a note about that in v3. I'd propose to add something similar to:
* resizing is possible
* shrinking: Implementations can consider to delete chunks if the store allows this, or keep them. This should be communicated well to the user.
* increasing: If no data existed previously for the new areas, they implicitly have the fill value now. Previous partial chunks will contain the fill value at the time of writing them. If there was chunk data before for the new areas, this data will be shown. The latter case should be signalled to the user appropriately.

cc @DennisHeimbigner @jbms
