### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jakirkham** [zarr-developers/zarr-specs#2]
Currently we don't have a license here.

Many other projects in this org have chosen MIT, which might make sense. N5 uses BSD 2-Clause. Other Zarr/N5 projects use various license from MIT through Apache. Maybe one of these makes sense.

As a counterpoint, the idea of this repo is to include documents, not code. Perhaps it would be better to pick a different license given the intended usage. One of the [CC licenses]( https://creativecommons.org/licenses/ ) might be a reasonable choice.

There could be other choices that I've missed that would be relevant to discuss. Feel free to mention ideas here and we can try to reach consensus on one.

**Comment by alimanfoo** [comment]
I'm very far from being a license expert, but I believe it's common to use a CC license for documentation. I think I would vote for CC BY as it is least restrictive.

**Comment by jakirkham** [comment]
That seems fine to me as well.

They also have [CC0]( https://creativecommons.org/share-your-work/public-domain/cc0/ ), which is basically a public domain license with a fallback in countries that don't support public domain. Just as another permissive option.

**Comment by joshmoore** [comment]
As a vote for CC-BY, though OME uses both GPL and BSD code for different components the [spec](https://github.com/ome/ome-model/blob/master/specification/src/main/resources/released-schema/2016-06/ome.xsd#L14) uses http://creativecommons.org/licenses/by/3.0/ (There _has_ been a case of that spec being copied wholesale without attribution.)

**Comment by jakirkham** [comment]
Personally I'm less worried about attribution. The point of a spec IMO is to provide a scheme for standardization. If other people want to copy and reuse the spec, that's a good thing as it means more people are conforming to it. So CC0 seems fine to me. Though would also be ok with CC-BY.

**Comment by alimanfoo** [comment]
So technically, how would we implement a CC license for this repo? Do we create a "LICENSE" file with the license text like a code repo would do? Or is there a smarter way, e.g., linking to the [CC URL](https://creativecommons.org/licenses/by/3.0/)?

**Comment by jakirkham** [comment]
Agree with just adding the license file.

Would probably go with the `.txt` extension, but this is a minor point.

**Comment by jakirkham** [comment]
Where did we land on license choice?

**Comment by jakirkham** [comment]
Would it be fair to say the consensus is CC-BY?

**Comment by jakirkham** [comment]
Thoughts on my question above @zarr-developers/core-devs? I think if we want more people to get involved we need to have a clear license.

**Comment by alimanfoo** [comment]
CC-BY is what I've proposed in #16. I think we could close this issue as resolved in favour of CC-BY unless any objections within the next day or so.

**Comment by jakirkham** [comment]
Sounds good. Thanks for addressing that Alistair. 🙂

**Comment by jakirkham** [comment]
I went ahead and put the license text in PR ( https://github.com/zarr-developers/zarr-specs/pull/36 ). Hope that is ok. That may be easier for orgs to review.

**Comment by alimanfoo** [comment]
Thanks @jakirkham, seems like a good idea to include the license text file in the repo, as well as assert the license within each individual spec document.
