### ISSUE TITLE
V2 node_type values

### ISSUE THREAD

**Issue by DennisHeimbigner** [zarr-developers/zarr-specs#252]
Currently, for V3, the only defined value for the "node_type" JSON field is "array".
I think this needs to be extended to also allow the value "group".

**Comment by jbms** [comment]
Under the group metadata, the `node_type` of `"group"` is specified.

https://github.com/zarr-developers/zarr-specs/blob/46ed6cd12a4ae1618e2fa290cc168d7433f632a6/docs/v3/core/v3.0.rst?plain=1#L822

I agree though that there is room for confusion in that we document the array and group metadata requirements independently.
