### ISSUE TITLE
ZEP0001 status clarification, not "Final"?

### ISSUE THREAD

**Issue by mkitti** [zarr-developers/zarr-specs#265]
#260 and #261 marked ZEP0001 as `Accepted`.

![image](https://github.com/zarr-developers/zarr-specs/assets/8062771/415f86d3-93b0-4e2b-8bc9-dbab12514b0d)

ZEP0000 suggests that the status should now be `Final`.

> Once a Specification ZEP has been Accepted, the second PR which was submitted in the [zarr-specs](https://github.com/zarr-developers/zarr-specs) repository must be merged. After that, the status will be changed to Final.

However, #263 and #264 seem to be approaching ZEP0001 as if it were `Provisionally Accepted` which is a state which is not supposed to apply to "core" specifications.

What kind of changes are permitted to ZEP0001 when it is `Accepted` but not yet `Final`? When does ZEP0001 become `Final`?  Are (minor) breaking changes are permitted in the `Final` state?

**Comment by mkitti** [comment]
@MSanKeys963 , ping. Could you clarify the current state.

**Comment by MSanKeys963** [comment]
Hi @mkitti. 👋🏻 

> Could you clarify the current state

Yes!

As discussed in the last [ZEP meeting](https://zarr.dev/zeps/meetings) (rolling notes [here](https://hackmd.io/ZilORe8AQvyqH6ArqDw0Cg#2023-10-19)), the ZEP0001 is currently `Accepted` by the ZIC and ZSC. 
Please check #227 for the votes.

The ZIC are currently in the implementation phase, and we're in a grace period (which will end soon) to accept minor changes to the specification.

Once we're sure that the implementors propose no additional changes, we will do a _quick_ round of voting, and after that ZEP0001 will be `Final`.

I hope that helps. Please let me know if there's anything else.

**Comment by MSanKeys963** [comment]
Closing this now.
