### ISSUE TITLE
Possible error in Chunk Encoding section

### ISSUE THREAD

**Issue by brandon-neth** [zarr-developers/zarr-specs#285]
In the second on the requirement for codecs to support `compute_encoded_representation_type`, there is the following sentence: "In the case of a decoded representation that is a multi-dimensional array, the shape and data type of the encoded representation must be computable based only on the shape and data type, but not the actual element values, of the encoded representation."

Is this is supposed to be "computable based only on the shape and data type but not the actual element value, of the _decoded_ representation?" The existing sentence seems tautological.

**Comment by jbms** [comment]
Yes, that is correct, thanks for pointing that out.  Do you want to submit a pr to fix it?

**Comment by brandon-neth** [comment]
> Yes, that is correct, thanks for pointing that out. Do you want to submit a pr to fix it?

Sure, I'll get it up for yall sometime tomorrow probably!
