### ISSUE TITLE
Support for arbitrary data type (non array)

### ISSUE THREAD

**Issue by mzundo** [zarr-developers/zarr-specs#322]
We have been asked to consider ZARR container format for our data which includes/consist of not geospatial/non-array data but we have problems as it is clear that the "array" heritage of the format has resulted in non flexible choices and ZARR is not well suited. We need

1.  _natural_ support of arbitrary non-array data in they native format
2. direct semantically meaningful mapping to filesystem of the data allow data manipulation without any API

Until now we used simpler containers (SAFE format) which directly mapped on the filesystem as a collection of arbitrary files in a set of directories (both data and metadata) which allowed us total freedom to store data files in they **native** format maintaining a direct relation at filesystem level. We fundamentally want to be able to store some of our externally generated files in the original format with the original filename. Data could be sparse data, poligons, documentation, code, bitstreams, algorithms.  Direct identification and management of these file at filesystem level with semantically meaningful names is critical for our workflow. So if we unzip the product and navigate in the directory structure we would recognise our files directly and would be able to manipulate/copy/edit them directly.  Having the data chucked and put blindly in files called 0.0,   0.1, etc  is silly and would not work for us.

btw We are having a similar discussion with the use of STAC  catalogue that also does not support this type of data. For that we are considering OGC Record API that allows arbitrary catalogue data (could be a catalogue of books instead of satellite images).

Is there any _clean_ way to do it in ZARR ?

**Comment by jbms** [comment]
It sounds like you just want a filesystem or key-value/object store.  What are you hoping to achieve from zarr?  Do you just want some way to mark a zarr group/ directory as containing arbitrary files?

**Comment by rabernat** [comment]
Welcome @mzundo! 👋 

> We 

Who is "we"?

> have been asked

By whom?

> to consider ZARR container format for our data 

What sort of data?

>  Data could be sparse data, poligons, documentation, code, bitstreams, algorithms.

- Sparse array support has been discussed and is feasible in Zarr but not implemented
- Polygons can definitely be supported. We use [CF encoding](https://cf-xarray.readthedocs.io/en/latest/geometry.html) for this
- Documentation - sounds like a good fit for Zarr metadata
- bistreams - Zarr can store raw byte arrays
- code & algorithms - why would you want to but code and algorithims inside a data format? doesn't sound like a good idea

---

Zarr is meant for storing structured array data and associated metadata. It is often beneficial for users to use a structured data model, rather than distributing opaque files.

But if you really want a container to distribute arbitrary code, files, etc. together, zip file or tar.gz would be a good fit I guess.

**Comment by mzundo** [comment]
So summarizing the answer Zarr is not, like I suspected, adequate for the purpose of being a generic data format to support in a standardized way both geospatial information and associated non geospatial data.

If like I understand there is no plan ir way to make it more than a transport for arrays I will recommend not to use it.   Thanks for the answers.



I

**Comment by rabernat** [comment]
> Zarr is not, like I suspected, adequate for the purpose of being a generic data format to support in a standardized way both geospatial information and associated non geospatial data.

That's not what we said.

You arrived here with the assumption that Zarr was not a good fit for your application, asked some biased questions, declined to provide any details about your use case or requirements in response to our follow-up questions, and have now reached the predetermined conclusion you wished for. This doesn't feel like a constructive conversation.

Nevertheless, we wish you luck with you project. We're still curious to hear more details about your project and what file format you ultimately settle on if you care to share.
