### ISSUE TITLE
Enhancement Proposal Model

### ISSUE THREAD

**Issue by jakirkham** [zarr-developers/zarr-specs#43]
From discussion in issue ( https://github.com/zarr-developers/zarr/issues/291 ), there was interest in an Enhancement Proposal model. Would be good to discuss here how we make proposals, decide on proposals, track history, etc.

**Comment by joshmoore** [comment]
This also has a (positive) overlap with community/governance.

**Comment by jstriebel** [comment]
I assume this is covered by the ZEP (Zarr Enhancement Proposal) as described in [ZEP 0](https://zarr.dev/zeps/active/ZEP0000.html). Please feel free to re-open if this misses the point.
