### ISSUE TITLE
Core protocol v3.0 status

### ISSUE THREAD

**Issue by jrbourbeau** [zarr-developers/zarr-specs#53]
Hi All! 

I spent some time looking through the work surrounding the v3.0 core protocol over in https://github.com/zarr-developers/zarr-specs/pull/16. My goal for this issue is to summarize the current status of this work and help spur conversation in the community. Any feedback can then be used to guide and prioritize future work on the core protocol and protocol extensions.

cc @alimanfoo @jakirkham @joshmoore @ryan-williams 

### Specification development process document ([current status](https://github.com/zarr-developers/zarr-specs/pull/12))

- Defines concept of a core protocol, protocol extensions, stores, and codecs
- Will define the process for minor/major changes to the core protocol and how decisions are made
- Could use feedback from the community

### Core protocol ([current status](https://zarr-specs.readthedocs.io/en/core-protocol-v3.0-dev/protocol/core/v3.0.html))

- Core concepts and terminology
    - E.g. arrays, groups, chunks, etc.
    - These all seem to be well defined and in good shape overall

- Node names
    - Restriction to node name characters and some possible names
    - Case insensitive uniqueness of siblings
    - *Question:* Are the restrictions on node names too restrictive?

- Data types
    - Core data types are boolean, integer, and floating point
    - Complex and datetime dtypes can be implemented as protocol extensions
    - *Question:* What about languages that don't easily support the full list of core data types? (xref https://github.com/zarr-developers/community/issues/25)

- Chunking
    - Core protocol consists of regular grid. Other grid types, e.g. [non-uniform chunking](https://github.com/zarr-developers/zarr-specs/issues/40) or [unknown chunk sizes](https://github.com/zarr-developers/zarr-specs/issues/46), can be defined via protocol extensions
    - Core protocol uses C- and F-order for the memory layout of each chunk. Other layouts, e.g. [sparse memory layouts](https://github.com/zarr-developers/zarr-specs/issues/48), are possible via protocol extensions
    - Chunk encoding consists of a compressor codec. Note this does *not* include filters, which can be supported via protocol extensions

- Metadata
    - Three types of metadata documents: bootstrap metadata, array metadata, and group metadata
    - The bootstrap metadata doc must be encoded in JSON, while the array and group metadata docs can use other encodings
    - Bootstrap metadata document contains the protocol specification used (e.g. v3.0, v3.1, etc.), how the array and group metadata documents are encoded (default is JSON), and a list of protocol extensions used
    - Array metadata document contains the array shape, data type, user-defined attributes, etc. 
        - Protocol extension points include: data type, chunk grid type, and chunk memory layout
        - ``extensions`` metadata value need to be defined in protocol spec
        - *Question:* There seems to be a question about how to specify the ``fill_value`` for dtypes other than bool and int
    - Group metadata document contains protocol extensions and user-defined attributes

- Stores
    - Defines abstract store interface which can be implemented on top of different storage technology backends
    - Abstract interface methods for operating on keys and values in a store include `get`, `set`, `delete`, etc.
    - Not all abstract methods need to be implemented (e.g. can have a read-only store)
    - Core protocol does not define any store implementations, but gives examples of possible implementations
    - Some protocol operation need to be filled out

- Protocol extensions

    - This section needs to be completed

### Protocol extensions ([current status](https://zarr-specs.readthedocs.io/en/core-protocol-v3.0-dev/protocol/extensions.html))

Three protocol extensions are currently in progress:

- Datetime data types - looks relatively filled out
- Complex data types - currently a scaffolding
- Filters - currently a scaffolding

Several other possible extensions are outlined in https://github.com/zarr-developers/zarr-specs/issues/49

### Stores ([current status](https://zarr-specs.readthedocs.io/en/core-protocol-v3.0-dev/stores.html))

- Currently one store spec in progress, the file system store

**Comment by alimanfoo** [comment]
Thanks @jrbourbeau, this is a great summary of current status.

One thing I've been meaning to add for a while but haven't got around to yet is an example of a codec spec, e.g., for gzip. It would be just for illustration, so there is a concrete example of what we mean by a codec spec, and what a codec spec might look like.

Re the questions you highlight, maybe we could break them out into separate issues? Could label them as [core-protocol-v3.0](https://github.com/zarr-developers/zarr-specs/labels/core-protocol-v3.0) so it's clear they're part of discussion of the v3 core protocol, rather than something else? (And we probably need some general way of categorising issues to help with triage?)

**Comment by abergou** [comment]
I have a question regarding non-uniform chunking: are the protocol extensions something that would need to be incorporated into a future version of the zarr spec (say zarr spec 3.5 or spec 4); or is the plan to expose an api that would allow for the definition of "fancier" arrays with spec 3? If the latter then do you know the status of exposing such functionality within zarr?
