### ISSUE TITLE
Terminology comparison with TensorStore

### ISSUE THREAD

**Issue by alimanfoo** [zarr-developers/zarr-specs#58]
The [TensorStore docs](https://google.github.io/tensorstore/index_space.html) include a documentation page defining some key terminology about ND arrays, including "index space", "index domain" and "index transformation". Maybe worth considering whether to adopt any of this terminology within the v3 core protocol spec.

**Comment by jstriebel** [comment]
@jbms I guess you can assess this best, is there something we should use in the spec? If not we can probably close this.

**Comment by jbms** [comment]
I think we can close this.
