### ISSUE TITLE
Support suffix for metadata files

### ISSUE THREAD

**Issue by alimanfoo** [zarr-developers/zarr-specs#63]
In the current v3 core protocol draft, keys for metadata documents have no suffix to represent the document format, they are just keys like "meta/root/foo.group" and "meta/root/foo/bar.array". In some situations (e.g., where file systems or web servers are being used as storage) it would be useful to have a suffix that indicates the format, i.e., ".json" for the default. Consider adding support for this.

**Comment by Carreau** [comment]
Add something like :
```
"metadata_key_suffix": ".json",
```

**Comment by jbms** [comment]
An alternative is that the extension is determined by `metadata_encoding`.  E.g. for the default `metadata_encoding` the extension is `.json`, and for a hypothetical cbor metadata encoding the extension would be `.cbor` or something.

As the spec is right now, if you specify a non-default `metadata_encoding` then the default `metadata_key_suffix` of `.json` is probably not appropriate.

**Comment by jstriebel** [comment]
The default `zarr.json` metadata now has a `.json` suffix, other metadata formats with different suffixes can be added via group extensions, see #37.
