### ISSUE TITLE
Misc. Minor Comments from Dennis Heimbigner

### ISSUE THREAD

**Issue by DennisHeimbigner** [zarr-developers/zarr-specs#74]
* A prediction :-)  It appears that rst format does not support numbered section headers. I suspect that you will come to want them later. GoogleDocs made the same mistake.
* Some time ago I was involved in the specification
of the DAP4 protocol. This was a large and reasonably
complex specification.
It might be useful for others to see how DAP4 was specified
in case it might be of use in specifying Zarr V3.
    * Volume 1: Data Model, Persistent Representation, and Constraints:
        https://docs.opendap.org/index.php?title=DAP4:_Specification_Volume_1
    * Volume 2: Web Services Specification
        https://docs.opendap.org/index.php?title=DAP4:_Specification_Volume_2
    * Volume 3: DAP4 Extensions
        https://docs.opendap.org/index.php?title=DAP4:_Specification_Volume_3

**Comment by jstriebel** [comment]
Thanks for the comments @DennisHeimbigner! We might tackle this again as part of #179, but sticked to the current format to finalize the v3 spec content-wise first.
