### ISSUE TITLE
Option to use `/` as as separator instead of `.` in spec v3. 

### ISSUE THREAD

**Issue by Carreau** [zarr-developers/zarr-specs#78]
From @alimanfoo on today's meeting. 

Can we add the option to use `/` as as separator instead of `.` in spec v3 ?
This comme from the potential need on filesystem to limit the number of files in a directory, and using `/` would help. Even if it could be made store only this may need to be exposed through the protocol as other tools may be copying data from a filesystem to a cloud store.

My main concern would then be the difficulty to know wether a path either given or returned from a store is an implict group, array or chunk. 

Say we have the following path: 

`/g1/g2/g3/a1/0.1.2.3.4`; it would become `/g1/g2/g3/a1/0/1/2/3/4` where I use here for clarity `g` for groups, `a` for array and numbers for chunks.

I think that a store or protocol implementation _may_ have the query at least `/meta/g1/g2/g3/a1/0/1/2/3/4/.array`, to `/meta/g1/g2/g3/a1/.array` potentially in order to know how to interpret a key. 

For example this may complicate things like `list_dir()` that now needs some understanding of the structure. Listing `/g1/g2/g3/a1/0/` should typically fail (it is not really a dir/group), unless we walk up to find the `.array`.

Listing `/g1/g2/g3/a1/` would return all the chunks in case where separator is `.`, only the number of chunks along the first dimension if separator is `/`, unless it is made aware of the separator.

This can likely be taken care of in the protocol, though that feel like extra complexity.

**Comment by Carreau** [comment]
I think that I missed the fact you only had check the metadata store for the existence of an array. So I agree I think we should be fine with allowing / as separator.

And yes 0 was s specific bad example chosen on purpose.

**Comment by joshmoore** [comment]
Sorry to have missed the call, but to just cross-link myself from https://github.com/zarr-developers/zarr-python/issues/395#issuecomment-458520137, I'd vote for having `/` as the _default_. I'm now up to 10s of millions of chunks in a single directory which for non-cloud purposes is essentially a non-starter. @alimanfoo's comment above seems to say that shouldn't be an issue, but just in case it might be, I thought I'd raise here.

**Comment by alimanfoo** [comment]
I would have no objection to "/" as the default.

**Comment by constantinpape** [comment]
I fully agree that "/" should be the default. Actually this is one of the reasons I still fall back to n5 most of the time, because it makes (default) zarr not really usable with large files.
(I know that there's `NestedDirectoryStore`, but it would be still be very nice to have this by default.)
