### ISSUE TITLE
v3 Spec: Finalize current codecs

### ISSUE THREAD

**Issue by Carreau** [zarr-developers/zarr-specs#87]
One of the TODO items in spec v3 is the process around adding codec.
Once https://github.com/zarr-developers/zarr-specs/pull/12 is resolved a link should be added in V3 "Chunk encoding" section.

**Comment by Carreau** [comment]
May want to add a placeholder spec for each of the codec we want to support. 
 - blosc ,lz4, zstd...

**Comment by jstriebel** [comment]
Part of #169.
