### ISSUE TITLE
V3 TBD: re-discuss "must understand".

### ISSUE THREAD

**Issue by Carreau** [zarr-developers/zarr-specs#88]
The "extensions" section of v3 states:

    An array containing zero or more objects, each of which identifies
    a protocol extension and provides any additional extension
    configuration metadata. Each object must contain the name
    ``extension`` whose value is a URI that identifies a Zarr protocol
    extension and dereferences to a human readable representation of
    the extension specification. Each object must also contain the
    name ``must_understand`` whose value is either the literal
    ``true`` or ``false``. Each object may also contain the name
    ``configuration`` whose value is defined by the protocol
    extension.

    If an implementation of this specification encounters an extension
    that it does not recognize, but the value of ``must_understand``
    is ``false``, then the extension may be ignored and processing may
    continue. If the extension is not recognized and the value of
    ``must_understand`` is ``true`` then processing must terminate and
    an appropriate error raised.

From previous discussions it seem like we agree "must understand" seem to restrictive, for example an extension may affect only a subset of arrays, or be required only to write array.

**Comment by Carreau** [comment]
Add a note that this is one of the area where feedback is wanted during RFC.

**Comment by jstriebel** [comment]
> From previous discussions it seem like we agree "must understand" seem to restrictive, for example an extension may affect only a subset of arrays, or be required only to write array.

The current mechanism allows to specify array-specific extensions per array, and not on the hierarchy level. My understanding is, that a zarr client could still open the hierarchy, even if some of the must-understand array extensions are not understood, and just could not open the affected arrays. Closing this therefore for now, please re-open if you feel this is not resolved @Carreau.
