### ISSUE TITLE
spec v3: codec and data type

### ISSUE THREAD

**Issue by davidbrochart** [zarr-developers/zarr-specs#96]
Do we assume that a codec must be able to encode/decode any data type? I can imagine a situation where a codec was designed to work for a very specific data type and nothing else (e.g. efficiently store a datetime).

**Comment by alimanfoo** [comment]
That is a good question.

It also raises the point that currently the [way we describe chunk encoding](https://zarr-specs.readthedocs.io/en/core-protocol-v3.0-dev/protocol/core/v3.0.html#chunk-encoding) assumes that a codec's encode function takes only a sequence of bytes as input, i.e., the codec is not aware of any other information about the input buffer such as it's type size or number of dimensions.

But we know there are some codecs that will want to access the type size at least, e.g., blosc. And so perhaps we should clarify that codecs may be aware of type size and implementations should ensure type size information is made available to codecs somehow. E.g., with Python this is supported via the buffer interface. Not sure the best way to explain this.

**Comment by davidbrochart** [comment]
> the codec is not aware of any other information about the input buffer such as it's type size or number of dimensions.

That's a good point, and I'm sure some compressors will want to take advantage of e.g. the spatial correlation in a 3D volume. So I think the compressor should basically have access to the whole array metadata. What do you think?
